name: 'Upload to Sauce Labs'
description: 'Upload files to Sauce Labs storage'
branding:
  icon: 'upload-cloud'
  color: 'gray-dark'

inputs:
  username:
    description: 'The Sauce Labs API username'
    required: true
  secret:
    description: 'The Sauce Labs API secret'
    required: true
  filename:
    description: 'The name of the file'
    required: true
  path:
    description: 'The path of the file'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        response=$(curl -u "${{ inputs.username }}:${{ inputs.secret }}" --location \
          --request POST 'https://api.eu-central-1.saucelabs.com/v1/storage/upload' \
          --form 'payload=@${{ inputs.path }}' \
          --form 'name=${{ inputs.filename }}')
        echo "$response"
      shell: bash
